In [1]:
import numpy as np

In [2]:
# create numpy array
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10], 
                [11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]])

# view array 
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
# check for some lists available in numpy.array.tolist().
print([1, 2, 3, 4, 5] in arr.tolist()) 
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 

True
False
False
True


In [16]:
# Creating 2X3 2-D Numpy array 
arr = np.array([[10.5, 22.5, 3.8],  
                [23.45, 50, 78.7], 
                [41, np.nan, np.nan]]) 
print(arr)

[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]


In [17]:
# Remove all rows containing non-numeric elements 
# isnan() returns ture or false , axis=1 represents row operation, axis=0 column operation 
# "~" operation is a bitwise NOT operator used for revese the boolean array returns form isnan() function
# arr[] This is the NumPy array indexing operation. 
# The boolean array ~np.isnan(arr).any(axis=1) is used to filter the rows of arr
# Only rows where the corresponding element in the boolean array is True are selected.
print(arr[~np.isnan(arr).any(axis=1)])

[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]]


In [24]:
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]]) 
#in_arr is a 3-dimensional NumPy array with the shape (1, 2, 3).
#It consists of one 2x3 matrix, where all elements are 2
print(in_arr)
print("shape of in array : " ,in_arr.shape)

out_arr = np.squeeze(in_arr)
#squeeze() is a NumPy function that removes any single-dimensional entries (dimensions with size 1) from the shape of an array.
print(out_arr)
#In in_arr, the first dimension has size 1, so it is removed.
# The resulting out_arr has a shape of (2, 3)
print("shape of out array : " ,out_arr.shape)

[[[2 2 2]
  [2 2 2]]]
shape of in array :  (1, 2, 3)
[[2 2 2]
 [2 2 2]]
shape of out array :  (2, 3)


in_arr = np.arange(9).reshape(1, 3, 3) creates a 3D array of shape (1, 3, 3). 

The first dimension has a size of 1, and the other two dimensions have a size of 3.

numpy.arange() is a function in the NumPy library that generates an array containing evenly spaced values within a given interval.

numpy.arange([start, ]stop, [step, ], dtype=None)

start (optional): The starting value of the interval. The default value is 0.

stop (required): The end of the interval. This value is not included in the array.

step (optional): The spacing between consecutive values. The default value is 1.

dtype (optional): The desired data type of the array elements. If not provided, it will be inferred from the other arguments. 

squeeze(in_arr, axis=0) removes the axis with a size of 1 at index 0.

The output array out_arr now has a shape of (3, 3)

If axis is not None, and an axis being squeezed is not of length 1.

In [27]:
in_arr = np.arange(9).reshape(1, 3, 3)
print(in_arr)
print("shape of input array : ",in_arr.shape)

out_arr = np.squeeze(in_arr, axis=0) 
print(out_arr)
print("shape of input array : ",out_arr.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
shape of input array :  (1, 3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of input array :  (3, 3)


repr(arr) converts the array to its string representation

.count("9, 4") counts the occurrences of the substring "9, 4" in this string representation.

In [3]:
arr = np.array([[2, 8, 9, 4],  
                [9, 4, 9, 4], 
                [4, 5, 9, 7], 
                [2, 9, 4, 3]])

output = repr(arr).count("9, 4")
print(output)

4


np.bincount(arr): bincount counts the number of occurrences of each value in the array arr. 

The result is an array where the index represents the value and the value at that index represents the count of that value in arr.

.argmax() returns the index of the maximum value in the array. 

In this case, it finds the index of the highest count, which corresponds to the most frequent value in the original array.

In [7]:
arr = np.array([1,2,3,4,9,1,2,1,1,1]) 
print("Original array:") 
print(arr)

value = np.bincount(arr)
print("the bitcount array is: ", value)

value = np.bincount(arr).argmax()

print("Most frequent value in the above array: ", value) 

Original array:
[1 2 3 4 9 1 2 1 1 1]
the bitcount array is:  [0 5 2 1 1 0 0 0 0 1]
Most frequent value in the above array:  1


np.nditer() This is an iterator object used for efficient multi-dimensional array iteration. 

It allows iterating over one or more arrays element by element.

In [9]:
arr_1d = np.arange(5) 
print("One dimensional array:") 
print(arr_1d) 
  
arr_2d = np.arange(10).reshape(2,5) 
print("\nTwo dimensional array:") 
print(arr_2d) 

for a, b in np.nditer([arr_1d, arr_2d]): 
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


meshgrid() generates coordinate matrices from the input arrays arr_1 and arr_2. 

It effectively creates a grid where each element from arr_1 is paired with each element from arr_2 and arr_3

".T" Transposes the 3D array so that the shape changes from.

.reshape(-1, 3): Reshapes the array into a 2D array with two columns and as many rows as there are pairs.

The -1 tells NumPy to automatically calculate the appropriate number of rows based on the total number of elements and the other dimension specified (3 in this case)

The 3 specifies that each row should have 3 elements.

In [32]:
# creating 2 numpy arrays 
arr_1 = np.array([1, 2, 4]) 
arr_2 = np.array([4, 6]) 
arr_3 = np.array([18, 17]) 
  
print("Array 1") 
print(arr_1) 
  
print("Array 2") 
print(arr_2)

print("Array 3") 
print(arr_3)


comb_array = np.array(np.meshgrid(arr_1, arr_2, arr_3)).T.reshape(-1, 3) 
  
print("\nCombine array:") 
print(comb_array) 

Array 1
[1 2 4]
Array 2
[4 6]
Array 3
[18 17]

Combine array:
[[ 1  4 18]
 [ 1  6 18]
 [ 2  4 18]
 [ 2  6 18]
 [ 4  4 18]
 [ 4  6 18]
 [ 1  4 17]
 [ 1  6 17]
 [ 2  4 17]
 [ 2  6 17]
 [ 4  4 17]
 [ 4  6 17]]


np.pad(): This function adds padding to an array. The padding can be added to any or all of the dimensions of the array.

Parameters:

array: The array that you want to pad.

pad_width=1: Specifies the number of values padded to the edges of each dimension. In this case, 1 means one element is added to each side (both before and after) of the array's dimensions.

mode='constant': Specifies the type of padding. Here, 'constant' means that the padding values are constant, as opposed to other modes like 'reflect', 'symmetric', or 'wrap'.

constant_values=0: Specifies the value to be used for the padding. In this case, 0 is used, so the padding consists of zeros.

In [38]:
# Creating a 2X2 Numpy matrix 
array = np.ones((2, 2), dtype=int) 
print("Original array") 
print(array)

array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("array after adding padding")
print(array)

Original array
[[1 1]
 [1 1]]
array after adding padding
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


all() method check the array in comparison and return true or flase accordingly

In [3]:
arr_one = np.array([[1, 2], [3, 5]])
arr_two = np.array([[1, 2], [3, 4]])
 
comparison = arr_one == arr_two
equal_arrays = comparison.all()
 
print(equal_arrays)

False


we can check a spectic number is availaabe in  array or not using "in"

In [4]:
# creating a Numpy array 
my_arr = np.array([[4, 5.5, 7, 6.9, 10], 
					[7.1, 5.3, 40, 8.8, 1], 
					[4.4, 9.3, 6, 2.2, 11], 
					[7.1, 4, 5, 9, 10.5]]) 


print("Given array:") 
print(my_arr) 

# Checking whether specific values 
# are present in "my_arr" or not 
print(2.14 in my_arr) 
print(5.28 in my_arr) 
print(8.5 in my_arr) 


Given array:
[[ 4.   5.5  7.   6.9 10. ]
 [ 7.1  5.3 40.   8.8  1. ]
 [ 4.4  9.3  6.   2.2 11. ]
 [ 7.1  4.   5.   9.  10.5]]
False
False
False


np.diagonal(arr, axis1=1, axis2=2) extracts the diagonal elements from each 2D slice along the specified axes (axis1=1 for rows and axis2=2 for columns).

In [9]:

# Create 3D-numpy array  of 4 rows and 4 columns 
arr_3d = np.arange(3 * 4 * 4).reshape(3, 4, 4) 

print("Original 3d array:\n", arr_3d) 

# Create 2D diagonal array 
arr_diag = np.diagonal(arr_3d, axis1 = 1, axis2 = 2) 

print("2d diagonal array:\n", arr_diag)


Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


In [14]:
# declare matrix with np 
arr_1st = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]]) 
print("Original array \n", arr_1d)
# using array.flatten() method 
flat_arr_1st = arr_1st.flatten(order='A') 
print("Flatten array \n",flat_arr_1st) 


Original array 
 [[ 6  9 12]
 [ 8  5  2]
 [18 21 24]]
Flatten array 
 [ 6  9 12  8  5  2 18 21 24]


we can use moveaxis() to move the axis of a array it takes array , initial index and final index as output

In [18]:
arr = np.zeros((1, 2, 3, 4)) 
# moving axis and getting shape of array
arr_2nd = np.moveaxis(arr, 0, -1).shape 
print (arr_2nd) 


(2, 3, 4, 1)


In [19]:
# numpy.swapaxes() function 
arr_1st = np.array([[2, 4, 6]]) 
arr_2nd = np.swapaxes(arr_1st, 0, 1) 
print (arr_2nd) 


[[2]
 [4]
 [6]]


In [24]:
# numpy.swapaxes() function 
arr_1st = np.array([[1, 2, 3],[4, 5, 6]]) 
arr_2nd = np.swapaxes(arr_1st, 0, 1) 
print (arr_2nd) 


[[1 4]
 [2 5]
 [3 6]]


In [27]:
# We are creating an array contains n elements 
# for getting first 'n' Fibonacci numbers 
fNumber = int(input("Enter the value of n + 1'th number : ")) 
a = np.arange(1, fNumber) 
length_a = len(a) 
# splitting of terms for easiness 
sqrt_five = np.sqrt(5) 
alpha = (1 + sqrt_five) / 2
beta = (1 - sqrt_five) / 2

# Implementation of formula 
# np.rint is used for rounding off to integer 
fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrt_five)) 
print("The first {} numbers of Fibonacci series are {} . ".format(length_a, fn)) 

[1 2 3 4 5 6 7 8 9]
The first 9 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34.] . 


In [29]:
# numpy.count_nonzero() function, give the count of non zero values in numpy array

arr_1st = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]] 

arr_nonzero = np.count_nonzero(arr_1st) 

print (arr_nonzero) 


6


In [31]:
# Python program explaining
# numpy.size() method 
# Making a random array 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# count the number of elements along the axis.
# Here rows and columns are being treated
# as elements
print(np.size(arr)) 
#gives no. of rows along x-axis
print(np.size(arr, 0)) 

#gives no. of columns along y-axis
print(np.size(arr, 1)) 


8
2
4


In [32]:
arr_1st = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 

# without trim parameter 
# returns an array without leading and trailing zeros 
print
arr_nonzero = np.trim_zeros(arr_1st) 
print("without zero: "arr_nonzero) 


[ 1  5  7  0  6  2  9  0 10]


In [36]:
# Create a numpy array 
arr = np.array([10, 20, 30, 40, 50]) 
# Print the array 
print(arr)
# Print the dtype 
print(arr.dtype)
# change the dtype to 'float64' 
arr = arr.astype('float64') 

# print the data type 
print(arr.dtype)


[10 20 30 40 50]
int32
float64


In [39]:
# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# printing initial ini_array
print("initial array", str(ini_array))

# printing type of ini_array
print("type of ini_array", type(ini_array))

# using shortcut method to reverse
res = np.flip(ini_array)
 
# printing result
print("final array", str(res))

# using shortcut method to reverse
res = ini_array[::-1]

# printing result
print("final array", str(res))
# using flipud method to reverse
res = np.flipud(ini_array)
 
# printing result
print("final array", str(res))


initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]
final array [5 4 6 3 2 1]
final array [5 4 6 3 2 1]


In [42]:
a = np.zeros(11)
print("Before any change ")
print(a)

a[1] = 2
print("Before after first change ")
print(a)

a.setflags(write=False)
print("After making array immutable on attempting second change ")
# a[1] = 7


Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable on attempting second change 
