In [15]:
import numpy as np

In [2]:
#using empty() function we can create empty array
empty_array_2d = np.empty([3, 4])
#np.empty(m,n) where m is number of rows and n is number of columns.
print(empty_array_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#unsing full() function we can create full array of defined number
full_array_2d = np.full([3, 4], 1, dtype = int)
print(full_array_2d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


shape : integer or sequence of integers

order  : C_contiguous or F_contiguous

         C-contiguous order in memory(last index varies the fastest)

         C order means that operating row-rise on the array will be slightly quicker

         FORTRAN-contiguous order in memory (first index varies the fastest).
         
         F order means that column-wise operations will be faster. 

dtype : [optional, float(byDeafult)] Data type of returned array.

In [17]:
#creating array with zeros() function
full_array_1d = np.zeros(3, dtype = int)
print(full_array_1d)

[0 0 0]


In [18]:
full_array_2d = np.zeros([3,3], dtype = int)
print(full_array_2d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
#creating array with ones() function
full_array_1d = np.ones(3, dtype = int)
print(full_array_1d)

[1 1 1]


In [20]:
full_array_2d = np.ones([3,3], dtype = int)
print(full_array_2d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
