In [2]:
import numpy as np
from numpy import linalg as la

In [12]:
matrix = np.matrix([[1,2,3],
                    [4,5,6],
                    [7,8,9]], dtype=int)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
eigenvalue, eigenvector = la.eig(matrix)
print(eigenvalue)
print(eigenvector)
s , r = la.qr(matrix)
print(r)
eig = la.eigvals(matrix)
print(eig)
u,s,vh = la.svd(matrix)
print(u)
print(s)
print(vh)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
