In [1]:
import numpy as np
from numpy import linalg as la

In [9]:

# initialize vector
vec = np.arange(10)

# compute norm of vector
vec_norm = la.norm(vec)

print("Vector norm:")
print(vec_norm)

# initialize matrix
mat = np.array([[ 1, 2, 3],
			[4, 5, 6]])

# compute norm of matrix
mat_norm = la.norm(mat)

print("Matrix norm:")
print(mat_norm)

# compute matrix num along axis 
mat_norm = la.norm(mat, axis = 1)
 
print("Matrix norm along particular axis :")
print(mat_norm)


Vector norm:
16.881943016134134
Matrix norm:
9.539392014169456
Matrix norm along particular axis :
[3.74165739 8.77496439]


In [10]:

# Create a numpy array 
matrix = np.matrix([[5, 11, -15], [12, 34, -51], 
				[-24, -43, 92]], dtype=np.int32) 
	
print("original matrix \n", matrix) 

# Find the QR factor of array 
q, r = la.qr(matrix) 
print('\nQ:\n', q) 
print('\nR:\n', r) 



original matrix 
 [[  5  11 -15]
 [ 12  34 -51]
 [-24 -43  92]]

Q:
 [[-0.18318583 -0.08610905  0.97929984]
 [-0.43964598 -0.88381371 -0.15995231]
 [ 0.87929197 -0.45984624  0.12404465]]

R:
 [[-27.29468813 -54.77256208 106.06459346]
 [  0.         -11.22347731   4.06028083]
 [  0.           0.           4.88017756]]


In [11]:
# Creating a 4X4 matrix 
matrix = np.matrix([[4, 1, 4, 2], [3, 1, 2, 0], 
				[3, 5, 7 ,1], [0, 6, 8, 4]]) 

print("Original matrix: \n",matrix) 

# Output 
result = la.cond(matrix) 
print("Condition number of the matrix: ", result)  


Original matrix: 
 [[4 1 4 2]
 [3 1 2 0]
 [3 5 7 1]
 [0 6 8 4]]
Condition number of the matrix:  57.34043866386217


In [12]:
# create numpy 2d-array 
matrix = np.matrix([[1, 2, 3], 
			[2, 3, 4], 
			[4, 5, 6]]) 

print("Printing the Original square array:\n", matrix) 

# finding eigenvalues and eigenvectors 
eigenvalue, eigenvector = la.eig(matrix) 

# printing eigen values 
print("Printing the Eigen values of the given square array:\n", eigenvalue) 

# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n", eigenvector) 


Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [15]:
#finding Euclidean distance using linalg.norm()
# initializing points in
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))

# calculating Euclidean distance
dist = la.norm(point1 - point2)
# printing Euclidean distance
print("point1 : ",point1," point2 ", point2," Euclidean distance: ",dist)

# subtracting vector
temp = point1 - point2
# sum of the squares
sum_sq = np.dot(temp.T, temp)
dist = np.sqrt(sum_sq)
print("point1 : ",point1," point2 ", point2," Euclidean distance: ",dist)

# finding sum of squares
sum_sq = np.sum(np.square(point1 - point2))
dist = np.sqrt(sum_sq)
print("point1 : ",point1," point2 ", point2," Euclidean distance: ",dist)

point1 :  [1 2 3]  point2  [1 1 1]  Euclidean distance:  2.23606797749979
point1 :  [1 2 3]  point2  [1 1 1]  Euclidean distance:  2.23606797749979
point1 :  [1 2 3]  point2  [1 1 1]  Euclidean distance:  2.23606797749979
