In [4]:
import numpy as np
from numpy import linalg as la

numpy.matrix(data, dtype = None)
data  : data needs to be array-like or string 
dtype : Data type of returned array.

In [7]:
# import the important module in python 

# make a matrix with numpy 
mtx = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]') 

print("Matrix: \n" ,mtx)
# # max() function will give the largest element of matrix
mtx_max = mtx.max() 
	
print("max: ",mtx_max) 
# min() function will give the smallest element of matrix
mtx_min = mtx.min() 
	
print("min: ",mtx_min) 


Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
max:  9
min:  1


In [8]:
#using reshape function for generate proper matrix shape
matrix= np.arange(1,10).reshape((3, 3))

print(matrix) # Original matrix
print(matrix.shape) # Number of rows and columns of the said matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
matrix = np.array([[4, 3, 2], [8, 7, 6]])
rows = matrix.shape[0]
columns = matrix.shape[1]

print("Rows:", rows)
print("Columns:", columns)

rows, columns = matrix.shape
print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3
Rows: 2
Columns: 3


Syntax : matrix.take(index, axis); Return : Return matrix of selected indexe

In [28]:
# make matrix with numpy 
matrix = np.matrix('[4, 1, 12, 3, 4, 6, 7]') 
			
# applying matrix.take() method 
mat_att = matrix.take(2)
print(matrix) 
print(mat_att)

# make matrix with numpy 
matrix = np.matrix('[4, 1, 12; 3, 6, 7; 1, 9, 5]') 

mat_att = matrix.take(1, 1) 
print("2 by 3 matrix: \n",matrix)
print(mat_att) 


[[ 4  1 12  3  4  6  7]]
[[12]]
2 by 3 matrix: 
 [[ 4  1 12]
 [ 3  6  7]
 [ 1  9  5]]
[[1 6 9]]


In [31]:
# make matrix with numpy 
matrix = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
			
# applying matrix.sum() method 1 for row and 0 for column
mat_sum = matrix.sum(axis = 1) 

print(matrix,"\n", mat_sum) 


[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]] 
 [[14]
 [16]
 [15]]


In [34]:
# creating a 4X4 Numpy matrix 
matrix = np.array([[55, 25, 15, 41], 
					[30, 44, 2, 54], 
					[11, 45, 77, 11], 
					[11, 212, 4, 20]]) 

# Displaying the Matrix 
print("Numpy Matrix is: \n", matrix)
# selecting diagonal
diagonal = np.diagonal(matrix)
# calculating the Trace of a matrix 
trace = np.trace(matrix) 
print("diagonal element given 4X4 matrix: ", diagonal) 
print("Trace of given 4X4 matrix: ", trace) 

Numpy Matrix is: 
 [[ 55  25  15  41]
 [ 30  44   2  54]
 [ 11  45  77  11]
 [ 11 212   4  20]]
diagonal element given 4X4 matrix:  [55 44 77 20]
Trace of given 4X4 matrix:  196


In [38]:
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix \n", A)
print("Printing elements of second matrix \n", B)
 
# subtracting two matrix
sub_matrix = np.subtract(A, B)
print("Subtraction of two matrix \n", sub_matrix)


# Define two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print("matrix a \n", matrix_a, "\nmatrix b \n", matrix_b)
# Subtract the matrices
result = matrix_a - matrix_b
print("after subraction \n", result)

Printing elements of first matrix 
 [[1 2]
 [3 4]]
Printing elements of second matrix 
 [[4 5]
 [6 7]]
Subtraction of two matrix 
 [[-3 -3]
 [-3 -3]]
matrix a 
 [[1 2]
 [3 4]] 
 matrix b 
 [[5 6]
 [7 8]]
after subraction 
 [[-4 -4]
 [-4 -4]]


In [69]:
matrix = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : \n", matrix);
 
# Array to be added as column
column_to_be_added = np.array([[1], [2], [3]])
 
# Adding column to array using append() method
new_matrix = np.append(matrix, column_to_be_added, axis = 1) 
print ("resultant array \n",new_matrix)

# Adding column to array using append() method
new_matrix = np.concatenate([matrix, column_to_be_added], axis=1)
print ("resultant array \n",new_matrix)

# Adding column to array using append() method
#new_matrix = np.insert(matrix, 0, column_to_be_added, axis=1)
#print ("resultant array \n", new_matrix)
 
# Adding column to numpy array
new_matrix = np.hstack((matrix, column_to_be_added))
print ("resultant array \n", new_matrix)

# Adding column to numpy array
new_matrix = np.column_stack((matrix, column_to_be_added))
print ("resultant array \n", new_matrix)

initial_array : 
 [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array 
 [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]
resultant array 
 [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]
resultant array 
 [[ 1  2  3  1  2  3]
 [ 1  2  3 45  4  7]
 [ 1  2  3  9  6 10]]
resultant array 
 [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]
resultant array 
 [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [92]:
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : \n", ini_array);
 
# Array to be added as row
row_to_be_added = np.array([1, 2, 3])
 
# Adding row to numpy array
result = np.r_[ini_array,[row_to_be_added]]
print("resultant array \n", result)

#last row
row_n = arr.shape[1] 
arr = np.insert(ini_array,row_n,[row_to_be_added],axis= 0)
print("resultant array \n", result)

# Adding row to numpy array
result = np.vstack ((ini_array, row_to_be_added))
print("resultant array \n", result)

empt_array = np.empty((0,2), int)
print("Empty array: \n", empt_array)
empt_array = np.append(empt_array, np.array([[10,20]]), axis=0)
empt_array = np.append(empt_array, np.array([[40,50]]), axis=0)
print("resultant array \n", empt_array)


initial_array : 
 [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array 
 [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]
resultant array 
 [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]
resultant array 
 [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [ 1  2  3]]
Empty array: 
 []
resultant array 
 [[10 20]
 [40 50]]


In [3]:
# creating two matrices 
p = np.matrix([[1, 2], [2, 3], [4, 5]])
q = np.matrix([[4, 5, 1], [6, 7, 2]]) 
print("Matrix p : \n",p) 

print("Matrix q : \n",q)  
  
# computing product 
result = np.dot(p, q) 
print("The dot product is :\n",result) 

result =  p @ q
print("The dot product is :\n",result) 

Matrix p : 
 [[1 2]
 [2 3]
 [4 5]]
Matrix q : 
 [[4 5 1]
 [6 7 2]]
The dot product is :
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
The dot product is :
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [13]:
matrix = np.matrix([[1, 2, 3],[4, 5, 6], [7, 9, 9]]) 
print("matrix: /n", matrix)
#calculationg eigenvalues
eigenval = la.eigvals(matrix)
print("eigenvalue is: ", eigenval)
#calculating determinant
determnt = la.det(matrix)
print("determinant is: ", determnt)
#calculating inverse
inv_matrix = la.inv(matrix)
print("inverse matrix is \n", inv_matrix)

matrix: /n [[1 2 3]
 [4 5 6]
 [7 9 9]]
eigenvalue is:  [16.47853607 -1.16635961 -0.31217646]
determinant is:  5.999999999999997
inverse matrix is 
 [[-1.5         1.5        -0.5       ]
 [ 1.         -2.          1.        ]
 [ 0.16666667  0.83333333 -0.5       ]]


In [19]:
ini_array = np.array([10, 20, 5,10, 8, 20,8, 9])
 
# Get a tuple of unique values 
# and their frequency in
# numpy array
unique, frequency = np.unique(ini_array, return_counts = True)
# print unique values array
print("Unique Values:", unique)
# print frequency array
print("Frequency Values:",frequency)

 
# convert both into one numpy array
count = np.asarray((unique, frequency ))
print("The values and their frequency are:\n",count)

# convert both into one numpy array and then transpose it
count = np.asarray((unique,frequency )).T
print("The values and their frequency are in transpose form:\n",count)

#Get unique values and their counts using bincount
unique_values = np.unique(ini_array)
counts = np.bincount(ini_array)
 
# Display the results
print("Unique Values:", unique_values)
print("Counts:", counts[unique_values])

from collections import Counter
# Use Counter to count occurrences
counts = Counter(ini_array)
# Display the results
print("Unique Values:", list(counts.keys()))
print("Counts:", list(counts.values()))

Unique Values: [ 5  8  9 10 20]
Frequency Values: [1 2 1 2 2]
The values and their frequency are:
 [[ 5  8  9 10 20]
 [ 1  2  1  2  2]]
The values and their frequency are in transpose form:
 [[ 5  1]
 [ 8  2]
 [ 9  1]
 [10  2]
 [20  2]]
Unique Values: [ 5  8  9 10 20]
Counts: [1 2 1 2 2]
Unique Values: [10, 20, 5, 8, 9]
Counts: [2, 2, 1, 2, 1]


In [20]:
# creating matrix of complex number
x = np.array([[2+3j, 4+5j], [4+5j, 6+7j]])
y = np.array([[8+7j, 5+6j], [9+10j, 1+2j]])
print("Printing First matrix: \n",x)
print("Printing Second matrix: \n",y)
# vector dot product of two matrices
z = np.vdot(x, y)
print("Product of first and second matrices are: \n",z)

Printing First matrix: 
 [[2.+3.j 4.+5.j]
 [4.+5.j 6.+7.j]]
Printing Second matrix: 
 [[8. +7.j 5. +6.j]
 [9.+10.j 1. +2.j]]
Product of first and second matrices are: 
 (193-11j)


In [26]:
# Creating two 3-D matrix
matrix1 = np.array([[2, 8, 2], [3, 4, 8], [0, 2, 1]])
matrix2 = np.array([[2, 1, 1], [0, 1, 0], [2, 3, 0]])
print("Original matrix1: \n",matrix1,"shape",matrix1.shape)
print("Original matrix2: \n",matrix2,"shape", matrix2.shape)
result = np.outer(matrix1, matrix2)
print("Outer Product of the two matrix is: \n",result,"shape",result.shape)


Original matrix1: 
 [[2 8 2]
 [3 4 8]
 [0 2 1]] shape (3, 3)
Original matrix2: 
 [[2 1 1]
 [0 1 0]
 [2 3 0]] shape (3, 3)
Outer Product of the two matrix is: 
 [[ 4  2  2  0  2  0  4  6  0]
 [16  8  8  0  8  0 16 24  0]
 [ 4  2  2  0  2  0  4  6  0]
 [ 6  3  3  0  3  0  6  9  0]
 [ 8  4  4  0  4  0  8 12  0]
 [16  8  8  0  8  0 16 24  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 4  2  2  0  2  0  4  6  0]
 [ 2  1  1  0  1  0  2  3  0]] shape (9, 9)


In [32]:
# Vectors 
a = np.array([2, 6]) 
b = np.array([3, 10]) 
print("a = ", a) 
print("b = ", b) 
# Outer product of vectors 
print("Outer product of vectors a and b") 
print(np.outer(a, b)) 

a =  [2 6]
b =  [ 3 10]
Outer product of vectors a and b
[[ 6 20]
 [18 60]]


In [34]:
# Vectors 
a = np.array([3, 6]) 
b = np.array([9, 10]) 
print("Vectors :") 
print("a = ", a) 
print("b = ", b) 
# Cross product of vectors 
print("Cross product of vectors a and b") 
print(np.cross(a, b)) 
# Matrices 
x = np.array([[2, 6, 9], [2, 7, 3]]) 
y = np.array([[7, 5, 6], [3, 12, 3]]) 
print("Matrices :") 
print("x =", x) 
print("y =", y) 

# Cross product of matrices 
print("Cross product of matrices x and y") 
print(np.cross(x, y)) 


Vectors :
a =  [3 6]
b =  [ 9 10]
Cross product of vectors a and b
-24
Matrices :
x = [[2 6 9]
 [2 7 3]]
y = [[ 7  5  6]
 [ 3 12  3]]
Cross product of matrices x and y
[[ -9  51 -32]
 [-15   3   3]]


In [37]:
array1 = np.array([2, 1, 1, 4]) 
array2 = np.array([2, 2, 1, 1])  
# Original array1 
print(array1) 
  
# Original array2 
print(array2) 
  
# Covariance matrix 
print("Covariance matrix of the said arrays:\n",  
      np.cov(array1, array2)) 
	
x = [1.23, 2.12, 3.34, 4.5] 
y = [2.56, 2.89, 3.76, 3.95] 
	
# find out covariance with respect rows 
#stack vertically rows
cov_mat = np.stack((x, y), axis = 1) 
	
print("shape of matrix x and y:", 
	np.shape(cov_mat)) 

print("shape of covariance matrix:", 
	np.shape(np.cov(cov_mat))) 

print(np.cov(cov_mat))


[2 1 1 4]
[2 2 1 1]
Covariance matrix of the said arrays:
 [[ 2.         -0.33333333]
 [-0.33333333  0.33333333]]
shape of matrix x and y: (4, 2)
shape of covariance matrix: (4, 4)
[[ 0.88445  0.51205  0.2793  -0.36575]
 [ 0.51205  0.29645  0.1617  -0.21175]
 [ 0.2793   0.1617   0.0882  -0.1155 ]
 [-0.36575 -0.21175 -0.1155   0.15125]]


In [38]:
# Creating arrays
array1 = np.array([[1, 2], [3, 4]])
print('Array1:\n', array1)
 
array2 = np.array([[5, 6], [7, 8]])
print('\nArray2:\n', array2)
 
# Computing the Kronecker Product
kroneckerProduct = np.kron(array1, array2)
print('\nArray1 ⊗ Array2:')
print(kroneckerProduct)

Array1:
 [[1 2]
 [3 4]]

Array2:
 [[5 6]
 [7 8]]

Array1 ⊗ Array2:
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


In [39]:
# make matrix with numpy 
matrix = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
              
# applying matrix.tolist() method 
matrix_lst = matrix.tolist() 
print("matrix: \n",matrix)
print("list : ", matrix_lst)

matrix: 
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
list :  [[4, 1, 9], [12, 3, 1], [4, 5, 6]]
